linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    check-shadowing: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosec
    - unused
    - deadcoderun
  timeout: 5m
  issues-exit-code: 1
